#!/bin/bash

#
# Copyright (c) 2021, MangDang Technology Co., Limited
#

#Power monitor
while true
do
	current_voltage=`cat /sys/class/power_supply/max1720x_battery/voltage_now`
	if [ $current_voltage -le 6500 ]; then
		GPIO_BASE=0
		[ -d /sys/class/gpio/gpiochip512 ] && GPIO_BASE=512
		echo 0 > /sys/class/gpio/gpio$((GPIO_BASE + 25))/value
		echo 0 > /sys/class/gpio/gpio$((GPIO_BASE + 21))/value
		# install scrip will replace BASEDIR
		mpg123 BASEDIR/Audio/low_power.mp3
		/usr/bin/display_low_battery.py 
	fi
	sleep 8
done
